### ISSUE TITLE
GSharpSample 컴파일 오류

### ISSUE THREAD

**Issue by Web-Engine** [iodes/GSharp#1]
GSharpSample 실행시,

> 컴파일 오류 : 9 - CS0234:'GSharp' 네임스페이스에 'Extension' 형식 또는 네임스페
> 이스 이름이 없습니다. 어셈블리 참조가 있는지 확인하십시오.
> 컴파일 오류 : 10 - CS0234:'GSharp' 네임스페이스에 'Extension' 형식 또는 네임스페
> 이스 이름이 없습니다. 어셈블리 참조가 있는지 확인하십시오.
> 컴파일 오류 : 22 - CS0246:'Application' 형식 또는 네임스페이스 이름을 찾을 수 없
> 습니다. using 지시문 또는 어셈블리 참조가 있는지 확인하십시오.
> 컴파일 오류 : 24 - CS0246:'Window' 형식 또는 네임스페이스 이름을 찾을 수 없습니
> 다. using 지시문 또는 어셈블리 참조가 있는지 확인하십시오.

와 같은 오류가 나타납니다.

**Comment by iodes** [comment]
8bfd282c28f089c11cec6b7a45fbba0423c7313b : 기본 참조를 자동으로 복사하도록 수정하였습니다.
