### ISSUE TITLE
만든 프로그램이 실행중일 때 덮어 써서 컴파일하면 프로그램이 죽어버리는 문제

### ISSUE THREAD

**Issue by ghost** [iodes/GSharp#13]
이미 만든 프로그램에 덮어쓰기로 사용할 경우 프로그램이 죽어버립니다.

![20171001_234821](https://user-images.githubusercontent.com/19469996/31055841-0ff019f2-a704-11e7-8bb8-aac87902bab5.png)

![20171001_234932](https://user-images.githubusercontent.com/19469996/31055843-17dd20e2-a704-11e7-8d64-a0233d1e0ecb.png)

디버깅 해보니 다른 프로세스에서 GSharp.Moudules.Core.IO.dll 파일을 사용 중이여서 프로그램이 죽어버렸습니다.

![20171001_235103](https://user-images.githubusercontent.com/19469996/31055851-524a903e-a704-11e7-899f-952de6d94ebf.png)

프로그램을 종료하는 블록도 추가와 함께 사용중일 경우 디버깅 실패나 다른 방법으로 오류를 처리해야할 듯합니다.

**Comment by iodes** [comment]
10c3a3fa2fa74d87d6bd82ba3e0b47325017fd82 : 컴파일 예외 처리 적용
컴파일 결과물이 종료되지 않는 오류는 별도의 이슈로 등록하였습니다.
