### ISSUE TITLE
샘플 프로그램 동작 오류

### ISSUE THREAD

**Issue by silvermix** [iodes/GSharp#5]
샘플 프로그램의 도구 상자에서 블럭이 드래그되지 않습니다.
프로그램 사용에 문제가 있으므로 수정해주시면 감사하겠습니다.

**Comment by iodes** [comment]
999f796c8c67ffc7ac0e0e86da80185077014b9d : 샘플 프로그램 도구 상자에서 블럭 드래그 구현
